### ISSUE TITLE
IPC mechanism

### ISSUE THREAD

**Issue by ghost** [JX7P/ServiceManager#33]
System XVI components need a way to intercommunicate: `s16.repositoryd` needs a way to send notifications of changes of state (new service additions, property changes, disablings, etc), s16.restartd needs a way to get service info from `s16.repositoryd`, and so on.

The original design for System XVI specified SunRPC as the mechanism for IPC. Is that the best choice? What are our alternatives for clean and simple communications?

**Comment by pid-0** [comment]
Here are some options:

- Roll our own. Maybe using XDR from SunRPC. This seems like it could be needlessly complex, but maybe not? We don't really need much complicated after all - We could 
- Capn'Proto. Very advanced, very modern, distributed objects sort of thing. But are our objects really distributed? It seems to me the Repository is the only place which should have a right to have real objects running around. 
- gRPC. It is very popular with Googlers.
- Soap, XML::RPC, CORBA, etc. These seem too heavyweight.
- Jason RPC.  Seems potentially good!

**Comment by pid-0** [comment]
I have decided to go with some kind of JSON-based RPC. We will wrap it all up in a simple C library, probably.

**Comment by rottrevore** [comment]
I take it that the project to create a Solaris SMF-esque for GNU/Linux and *BSD is back in the saddle again?

**Comment by JX7P** [comment]
@rottrevore it is indeed.

JSON-RPC 2.0 has been implemented now as the RPC of choice; it's simple and bindings exist for it everywhere. And we use libucl to parse our service config files, so we don't need to deal with another format this way.
